<a href="https://colab.research.google.com/github/priyanshigarg17/datascience/blob/main/Bodhak_Numpy_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

import numpy as np

NUmbers only: arrays

list = [1,2,3,4,5,6] converted into array like structure
in arrays, rows and columns

array = 1,2,3,4,5,6

Dataframes,consists of row as well as column labels (names)

Arrays of nunmbers, doesnt consists of row or column labels (names)

In [ ]:
#list of numbers
a = [1,2,3,4,5]
type(a)

Arrays: 1 dimensional (single row array)

If number of rows > 1, 2 D array

In [ ]:
import numpy as np
#np is the context manager for numpy
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)
a.ndim

1

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #list of lists
print(a)
#array with 4 rows and 4 columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)
#3 rows and 4 columns
a.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2

In [ ]:
#create an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones([2,2])
#array of ones

array([[1., 1.],
       [1., 1.]])

In [ ]:
list(range(10,25))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [ ]:
list(range(5,20,2)) #starting point will be 5
#python, end index positions are always exclusive

[5, 7, 9, 11, 13, 15, 17, 19]

In [ ]:
#arange is similar to range method of python
np.arange(10)
#number list from 0 in array format

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,16) #start, end point
#array of evenly spaced numbers

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(2,16,3) #start, end
#step or jump parameter

array([ 2,  5,  8, 11, 14])

In [ ]:
#generate linear data
np.linspace(5, 21,5) #start, end, number of values

array([ 5.,  9., 13., 17., 21.])

In [ ]:
#concatenation #joining
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print()
print(b)

np.concatenate((a, b))

[1 2 3 4]

[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
y = np.array([[5,6]])
y.ndim

In [ ]:
x = '3'
type(x)

str

In [ ]:
x = np.array([[1,2], [3,4], [7,8]])#array 0f 2 rows and 2 columns

y = np.array([[5,6],[9,10]])

print(x)
print()
print(y)

np.concatenate((x, y))

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
np.concatenate((x, y), axis=0)
#axis o is vertical axis

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
np.concatenate((x,y), axis=1)
#axis 1 is horizontal axis

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
x = np.array([[1,2], [3,4], [7,8]])#array 0f 2 rows and 2 columns

y = np.array([[5,6],[9,10],[11,12]])

print(x)
print()
print(y)

np.concatenate((x, y), axis=1)

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]
 [11 12]]


array([[ 1,  2,  5,  6],
       [ 3,  4,  9, 10],
       [ 7,  8, 11, 12]])

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5],[6]])
print(x)
print()
print(y)
np.concatenate((x,y), axis=1)

[[1 2]
 [3 4]]

[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print(x)
print()
print(y)

np.concatenate((x, y), axis=1)
#number of coulmsn will increase, extra columns

In [ ]:
x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print(x)
print(y)

np.concatenate((x, y), axis=0)
#number of rows will increase, add more rows

In [ ]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr)
#split command

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 10)
print(newarr)
#split command

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6], [7,8], [9,10], [11,12]])
arr
#2 D array with 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
print(newarr[0])

[[1 2]
 [3 4]]


In [ ]:
#split a 2darray into three 2d arrays along rows/accross columns
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#column wise splitting
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#row wise splitting
newarr = np.array_split(arr, 3, axis=0)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
print(newarr[0])

In [ ]:
print(newarr[1])

In [ ]:
#split a 2darray into three 2d arrays along rows/accross columns
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
newar = np.split(arr, 6)
print(newar)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [ ]:
#sorting of an array
arr = np.array([2,1,5,3,7,4,6,8])
ar = np.sort(arr)
#ascending order
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ar[::-1]#start,end,step

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#where #returning the positions (index values)
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
x = np.where(arr%2 == 0)
print(x)
#even

(array([1, 3, 5, 6]),)


In [ ]:
#odd
x = np.where(arr%2 == 1, 3)
print(x)

Dimeshion, Shape (number of rows and columns) and Size of array

In [ ]:
arr1 = np.array([[1,3,5,7], [2,4,6,8]])
print(arr1)

[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
#dimension
arr1.ndim

2

In [ ]:
arr1.size
#total number of elements present inside array

8

In [ ]:
arr1.shape
#number of rows and columns

(2, 4)

In [ ]:
#transpose of an array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
#flatten
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.flatten()#converting into 1D

array([1, 2, 3, 4])

In [ ]:
arr =np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
arr.flatten('F')

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [ ]:
#reshaping of an array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.reshape(a, newshape=(3,2))

In [ ]:
a.reshape(-1, 2)

In [ ]:
#1d to 2d
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#1d to 3D (outerdimension)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2, 2, 3)#no. of arrays, no. of rows, no. of columns
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
newarr.shape

In [ ]:
a = np.arange(72)
a=np.reshape(a, (4,3,2,3))#no. of blocks, arrays in each block, rows, columns

In [ ]:
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, -1, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr=np.arange(10)
newarr = np.split(arr, 3)  #this method works on equal distribution
print(newarr)

ValueError: array split does not result in an equal division

### Element wise arithmetic operations

In [ ]:
import numpy as np
#simple operators
data = np.array([1,2])

ones = np.ones(2, dtype=int)

a = np.array([3,4])

print(data)
print()
print(ones)
print(a)

[1 2]

[1 1]
[3 4]


In [ ]:
data + ones + a

array([5, 7])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * ones

array([1, 2])

In [ ]:
data / ones

array([1., 2.])

In [ ]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

print(a1, a2, sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
a1 + a2

array([[ 6,  8],
       [10, 12]])

In [ ]:
a1 - a2

array([[-4, -4],
       [-4, -4]])

In [ ]:
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [ ]:
a1 / a2

array([[0.2       , 0.33333333],
       [0.6       , 0.66666667]])

In [ ]:
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [ ]:
#2d arrays with different shapes
a1 = np.array([[1,2], [3,4,]])

a2 = np.array([[5,6]])

print(a1)
print()
print(a2)

[[1 2]
 [3 4]]

[[5 6]]


In [ ]:
a2 + a1

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
#2d array with different sizes
data = np.array([[1,2], [3,4,]])

datas = np.array([[5,6], [7,8], [8,9]])

print(datas)
print()
print(data)

[[5 6]
 [7 8]
 [8 9]]

[[1 2]
 [3 4]]


In [ ]:
data + datas

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.min()

np.int64(1)

In [ ]:
a = np.array([[5,6], [7,8], [8,9]])
a

array([[5, 6],
       [7, 8],
       [8, 9]])

In [ ]:
a.max()

np.int64(9)

In [ ]:
a.max(axis=0)
#axis 0 is vertical (top to bottom)

array([8, 9])

In [ ]:
a.max(axis=1)
#axis 1 is horizontal

array([6, 8, 9])

In [ ]:
a.min(axis=1)

In [ ]:
np.mean(a,axis=0)

array([6.66666667, 7.66666667])

In [ ]:
np.mean(a, axis=1)

array([5.5, 7.5, 8.5])

In [ ]:
np.median(a, axis=0)

array([7., 8.])

In [ ]:
 np.median(a,axis=1)

array([5.5, 7.5, 8.5])

### fetching elements based on conditions

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a[a < 5])
#within [] write the conditional expression

[1 2 3 4]


In [ ]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
print(a[a%2 == 0])

[ 2  4  6  8 10 12]


In [ ]:
print(a[a%2 != 0])

[ 1  3  5  7  9 11]


In [ ]:
print(a[(a > 2) & (a < 11)])
#and operator all conditions must be satisfied

[ 3  4  5  6  7  8  9 10]


In [ ]:
print(a[(a > 2) | (a < 11)])
#atleast one condition shall be satisfied

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Indexing and slicing

In [ ]:
import numpy as np
data = np.array([1,2,3])
print(data)

[1 2 3]


In [ ]:
data[2]

np.int64(3)

In [ ]:
data[0:2]#0, 1
#end position shall be exclusive

array([1, 2])

In [ ]:
data[1:]

In [ ]:
data[:3]#0-2

In [ ]:
data[::-1]

In [ ]:
dataone  = np.array([[1,2], [3,4,], [5,6]])
dataone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dataone[0]#row index position

array([1, 2])

row, column combinations: array[index position of rows, index position of columns]

In [ ]:
dataone[0,1]#o row and 1 column

np.int64(2)

In [ ]:
dataone[:,1]#all rows and 1st index column

array([2, 4, 6])

In [ ]:
dataone[1,0:2]#1st index row and 0th + 1st index column

array([3, 4])

In [ ]:
dataone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dataone[0:2, 1]

array([2, 4])

In [ ]:
dataone[0:1,0:2]

array([[1, 2]])