<a href="https://colab.research.google.com/github/priyanshigarg17/datascience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
#np is the context manager for numpy

a = np.array([1, 2, 3, 4, 5, 6])
a


array([1, 2, 3, 4, 5, 6])

In [8]:
type(a)
# a.ndim    #number of dimensions

numpy.ndarray

In [7]:
a= np.array([[1,2,3], [4, 5, 6], [7, 8, 9]]) #lists of list #same number of elements must
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
b = np.array([2,2,4,5])
b

array([2, 2, 4, 5])

In [12]:
c=np.array([[2,3,4,5], [5, 6, 7, 8], [9, 6, 7, 8]])
c

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [9, 6, 7, 8]])

In [13]:
#create an array of zeroes
np.zeros(3)

array([0., 0., 0.])

In [14]:
#array of ones
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [15]:
#arange is similar to range method of python
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5, 21, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
#generate linear data
np.linspace(5, 21, 5) #start, end , and number of values

array([ 5.,  9., 13., 17., 21.])

In [25]:
#concatenation #joining
a1=np.array([2, 3, 4, 5])
a2=np.array([5, 6, 7, 8])
print(a1)
print(a2)
np.concatenate((a1,a2))

[2 3 4 5]
[5 6 7 8]


array([2, 3, 4, 5, 5, 6, 7, 8])

In [27]:
x=np.array([[1, 2], [3, 4]])
y= np.array([[5,6]])  #casting = we chnage single row into 2D by putting brackets

#different dimensions = can not concatenate
np.concatenate((x,y))


array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.concatenate((x,y), axis=0) #vertical #default
#np.concatenate((x,y), axis =1) #horizontal  #not default

array([[1, 2],
       [3, 4],
       [5, 6]])